### ISSUE TITLE
Blade tree sitter failing

### ISSUE THREAD

**Issue by mokhosh** [kauffinger/lazyvim#10]
I just installed neovim, lazyvim, and then this config, and this is what I'm getting after following your instructions.

<img width="859" alt="Screenshot 2024-03-09 at 02 45 36" src="https://github.com/kauffinger/lazyvim/assets/6499685/e213cd65-d65f-4465-94db-f264ed04e35a">

Is this related to https://github.com/kauffinger/lazyvim/issues/7 ?

**Comment by kauffinger** [comment]
Your issue should not be related to #7, as I introduced your issue either by a recent commit or the author of tree-sitter-blade changed their branch naming recently - as back then installing worked.

Thanks again!
