### ISSUE TITLE
Incorrect cursor indentation in PHP files with `queries/php/indents.scm`

### ISSUE THREAD

**Issue by vietlubu** [kauffinger/lazyvim#17]
### Describe the Bug
When editing a PHP file in Neovim with the current queries/php/indents.scm configuration, adding a new line places the cursor at the beginning of the line instead of aligning it correctly with the surrounding code or block. This issue occurs even in cases where no custom indentation logic should apply.

### Steps to Reproduce
1. Open a PHP file in Neovim.
2. Press `o` to insert a new line.
3. Observe that the cursor starts at the beginning of the new line instead of being correctly indented.

### Screen shoot
![indents](https://github.com/user-attachments/assets/953badc7-414d-4250-90a1-4c00bc6d486a)

### Expected Behavior
The cursor should align with the surrounding indentation level or the current code block, as expected for most programming languages.

_Note_: If I remove `queries/php/indents.scm` file. the indent behavior is correct.

**Comment by kauffinger** [comment]
Thanks for reporting!
