### ISSUE TITLE
Error User Autocommands for "VeryLazy"

### ISSUE THREAD

**Issue by Romaixn** [kauffinger/lazyvim#5]
Hey! Thanks for this starter, I wanted to install it but I have an error with nvim-treesitter, do you know why?

```
Error detected while processing User Autocommands for "VeryLazy":
Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:86: Parser not available for language "help"
```

**Comment by kauffinger** [comment]
I've seen this error in my logs, too - in my experience it did not lead to issues, so I didn't look into it yet. You should be able to easily fix it if you remove 'help' from [this file](https://github.com/kauffinger/lazyvim/blob/main/lua/plugins/treesitter.lua)

Let me know if that worked and you are welcome!

**Comment by kauffinger** [comment]
Pushed that change along with some lockfile updates. Let me know if it works!

**Comment by Romaixn** [comment]
It's work! Thanks 🚀
